### ISSUE TITLE
ArrayIndexOutOfBoundsException on resize using triangle filter

### ISSUE THREAD

**Issue by Amooti** [openimaj/openimaj#95]
Using the following code:

```
final FImage fImage = ImageUtilities.createFImage(image);
fImage.processInplace(new ResizeProcessor(width, height, false, TriangleFilter.INSTANCE));
return ImageUtilities.createBufferedImage(fImage);
```

I get a the following exception:

```
java.lang.ArrayIndexOutOfBoundsException: 93
	at org.openimaj.image.processing.resize.ResizeProcessor.zoom(ResizeProcessor.java:900)
	at org.openimaj.image.processing.resize.ResizeProcessor.zoomInplace(ResizeProcessor.java:817)
	at org.openimaj.image.processing.resize.ResizeProcessor.processImage(ResizeProcessor.java:296)
	at org.openimaj.image.processing.resize.ResizeProcessor.processImage(ResizeProcessor.java:51)
	at org.openimaj.image.SingleBandImage.processInplace(SingleBandImage.java:206)
	...
```

This only happens with the TriangleFilter. I've attached an example image causing this error.

![example-image](https://cloud.githubusercontent.com/assets/668556/10134182/37c23c0c-65e4-11e5-9cdb-9dbe6bbc7933.jpg)

**Comment by jonhare** [comment]
What size are you trying to change the image to? also, what version of OpenIMAJ? Does the problem still exist with 1.4-SNAPSHOT?

**Comment by Amooti** [comment]
We're resizing it to 8x8. We've tried the 1.4-SNAPSHOT about two weeks ago, and the result was the same.

**Comment by jonhare** [comment]
Ok, it looks like there was a very peculiar rounding issue under some circumstances. Should be fixed in commit ea23aca5ca. A new snapshot should be building now & should be deployed within the next hour or so. Please reopen this issue if there are still problems.

**Comment by Amooti** [comment]
The problem still occurs, even after upgrading to version 1.3.8.

We're seeing the problem when resizing the following image
![problem-image](https://user-images.githubusercontent.com/668556/59996467-b0444d00-965a-11e9-93d5-0a7e2c77d7f6.jpg)
